[[pages]]
name = "Main Section"
icon = "ğŸ "
is_section = true

[[pages]]
path = "/ui/index.py"
name = "Home"
icon = "ğŸ "


[[pages]]
name = "Billing Section"
icon = "ğŸ“ƒ"
is_section = true

[[pages]]
path = "/ui/billing/index.py"
name = "Billing"
icon = "ğŸ“ƒ"


[[pages]]
name = "Analytics Section"
icon = "ğŸ’¸"
is_section = true

[[pages]]
path = "/ui/analytics/summary.py"
name = "Summary View"
icon = "ğŸ’¸"


[[pages]]
name = "Admin Section"
icon = "ğŸ¤–"
is_section = true

[[pages]]
path = "/ui/admin/admin.py"
name = "Home"
icon = "ğŸ "
